CREATE TABLE SONGS
(
    ID          VARCHAR(36)  NOT NULL,
    TITLE       VARCHAR(256) NOT NULL,
    ARTIST      VARCHAR(256) NOT NULL,
    GENRE       VARCHAR(64),
    PRIMARY KEY (ID)
);

CREATE TABLE LISTENED_SONGS
(
    ID               VARCHAR(36) NOT NULL,
    USER_ID          VARCHAR(36) NOT NULL,
    SONG_ID          VARCHAR(36) NOT NULL,
    LAST_LISTEN_DATE DATE        NOT NULL,
    TIMES_LISTENED   INT     NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SONG_ID) REFERENCES SONGS (ID) ON DELETE CASCADE
);
