CREATE TABLE LIVE_LISTENED_SONGS
(
    USER_ID VARCHAR(36) PRIMARY KEY,
    SONG_ID VARCHAR(36) NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    LATITUDE FLOAT NOT NULL,
    COUNTRY VARCHAR(124),
    CITY VARCHAR(124),
    REGION VARCHAR(124),
    LISTENED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (SONG_ID) REFERENCES SONGS(ID)
)